# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel
sudo: false
warnings_are_errors: true
cache: packages

bioc_packages: 
  - BiocInstaller
  - BiocCheck

addons:
  apt:
    update: true
    packages:
    - libmpfr-dev

after_success:
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck --new-package --no-check-vignettes updog*.tar.gz